// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func footer_main() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"py-12 bg-white xl:py-24 dark:bg-gray-800\"><div class=\"container px-4 mx-auto xl:px-0\"><div class=\"grid gap-12 xl:grid-cols-6 xl:gap-24\"><div class=\"col-span-2\"><a href=\"/\" class=\"flex mr-4\"><span class=\"self-center text-2xl font-semibold whitespace-nowrap dark:text-white\">Blox</span></a><p class=\"max-w-lg mt-4 text-gray-500 dark:text-gray-400\">Blox is the best app for construction!</p></div></div><hr class=\"my-8 border-gray-200 lg:my-12 dark:border-gray-700\"><span class=\"block text-center text-gray-600 dark:text-gray-400\">© 2017-<span id=\"currentYear\">2024</span> Blox. All Rights Reserved.</span></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
